In [22]:
import csv
import numpy as np
import pandas as pd
from sklearn.kernel_approximation import RBFSampler
from sklearn.linear_model import SGDClassifier
# from sklearn.cross_validation import train_test_split
from sklearn import svm
from sklearn.metrics import classification_report
from sklearn import metrics
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import (precision_score, recall_score,f1_score, accuracy_score,mean_squared_error,mean_absolute_error)
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import Normalizer
# from pandas_ml import ConfusionMatrix
from sklearn.metrics import confusion_matrix


In [32]:
def fixDataset(csvName):
    ids_1 = {"count":0}
    ids_2 = {"count":0}
    ids_3 = {"count":0}
    ids_4 = {"count":0}

    with open(csvName, 'r') as f:
        reader = csv.reader(f)
        text_file = open("newCsvDataset.txt", "w")
        for row in reader:
            for row_i in range(len(row)):
                text = ""
                if row_i == 1:
                    if row[row_i] in ids_1:
                        text = str(ids_1[row[row_i]])
                    else:
                        ids_1[row[row_i]] = ids_1["count"] 
                        ids_1["count"] += 1
                        text = str(ids_1[row[row_i]])

                elif row_i == 2:
                    if row[row_i] in ids_2:
                        text = str(ids_2[row[row_i]])
                    else:
                        ids_2[row[row_i]] = ids_2["count"] 
                        ids_2["count"] += 1
                        text = str(ids_2[row[row_i]])
                elif row_i == 3:
                    if row[row_i] in ids_3:
                        text = str(ids_3[row[row_i]])
                    else:
                        ids_3[row[row_i]] = ids_3["count"] 
                        ids_3["count"] += 1
                        text = str(ids_3[row[row_i]])
                elif row_i == 41:
                    if row[row_i] in ids_4:
                        text = str(ids_4[row[row_i]])
                    else:
                        ids_4[row[row_i]] = ids_4["count"] 
                        ids_4["count"] += 1
                        text = str(ids_4[row[row_i]])
                else:
                    text = row[row_i]

                text_file.write("{},".format(text))
            text_file.write('\n')

    return [ids_1,ids_2,ids_3,ids_4]

In [79]:
fixDataset("kddtrain.csv")

[{'count': 3, 'tcp': 0, 'udp': 1, 'icmp': 2},
 {'count': 70,
  'ftp_data': 0,
  'other': 1,
  'private': 2,
  'http': 3,
  'remote_job': 4,
  'name': 5,
  'netbios_ns': 6,
  'eco_i': 7,
  'mtp': 8,
  'telnet': 9,
  'finger': 10,
  'domain_u': 11,
  'supdup': 12,
  'uucp_path': 13,
  'Z39_50': 14,
  'smtp': 15,
  'csnet_ns': 16,
  'uucp': 17,
  'netbios_dgm': 18,
  'urp_i': 19,
  'auth': 20,
  'domain': 21,
  'ftp': 22,
  'bgp': 23,
  'ldap': 24,
  'ecr_i': 25,
  'gopher': 26,
  'vmnet': 27,
  'systat': 28,
  'http_443': 29,
  'efs': 30,
  'whois': 31,
  'imap4': 32,
  'iso_tsap': 33,
  'echo': 34,
  'klogin': 35,
  'link': 36,
  'sunrpc': 37,
  'login': 38,
  'kshell': 39,
  'sql_net': 40,
  'time': 41,
  'hostnames': 42,
  'exec': 43,
  'ntp_u': 44,
  'discard': 45,
  'nntp': 46,
  'courier': 47,
  'ctf': 48,
  'ssh': 49,
  'daytime': 50,
  'shell': 51,
  'netstat': 52,
  'pop_3': 53,
  'nnsp': 54,
  'IRC': 55,
  'pop_2': 56,
  'printer': 57,
  'tim_i': 58,
  'pm_dump': 59,
  'red_i':

In [41]:

print("***************************************************************")

traindata = pd.read_csv('kddtrain-20-mod.csv', header=None)
testdata = pd.read_csv('kddtest-mod.csv', header=None)

X = traindata.iloc[:,1:42]
Y = traindata.iloc[:,0]
C = testdata.iloc[:,0]
T = testdata.iloc[:,1:42]

scaler = Normalizer().fit(X)
trainX = scaler.transform(X)

scaler = Normalizer().fit(T)
testT = scaler.transform(T)


traindata = np.array(trainX)
trainlabel = np.array(Y)

testdata = np.array(testT)
testlabel = np.array(C)



***************************************************************


In [38]:
print("***************************************************************")

model = LogisticRegression()
model.fit(traindata, trainlabel)


# make predictions
expected = testlabel
predicted = model.predict(testdata)


print("***************************************************************")

***************************************************************


/Users/evanteters/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


***************************************************************


In [73]:
print("***************************************************************")

# fit a Naive Bayes model to the data
model = GaussianNB()
model.fit(traindata, trainlabel)
print(model)
# make predictions
expected = testlabel
predicted = model.predict(testdata)

cm = confusion_matrix(expected, predicted)
print(expected.shape)
print(predicted.shape)
expected = np.array(expected)
predicted = np.array(predicted)
# cm.print_stats()

np.savetxt('expected.txt', expected, fmt='%01d')
np.savetxt('predicted.txt',predicted , fmt='%01d')

print(cm)
print(expected.shape)
print(predicted.shape)
evaluateCM(cm)
# cm.stats()
print("***************************************************************")

***************************************************************
GaussianNB(priors=None, var_smoothing=1e-09)
(22544,)
(22544,)
[[4955   19    9 ...    0    0    0]
 [  50    2    1 ...    0    0    0]
 [  23    0    0 ...    0    0    0]
 ...
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]
 [   0    0    0 ...    0    0    0]]
(22544,)
(22544,)
Acc: 0.22130056738431864 prec: 0.0016383966783433057 recall: 0.003077566135099834 F1: 0.002138385874780905
***************************************************************


In [74]:
print("***************************************************************")
# fit a k-nearest neighbor model to the data
model = KNeighborsClassifier()
model.fit(traindata, trainlabel)
print(model)
# make predictions
expected = testlabel
predicted = model.predict(testdata)
# summarize the fit of the model

cm = metrics.confusion_matrix(expected, predicted)
print(cm)
tpr = float(cm[0][0])/np.sum(cm[0])
fpr = float(cm[1][1])/np.sum(cm[1])
print("%.3f" %tpr)
print("%.3f" %fpr)
evaluateCM(cm)
print("***************************************************************")




***************************************************************
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')
[[18888    62    15 ...     0     0     0]
 [  556    22     5 ...     0     0     0]
 [   99     3     0 ...     0     0     0]
 ...
 [    0     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]
 [    1     0     0 ...     0     0     0]]
0.993
0.037
Acc: 0.8389371879936538 prec: 0.0022566436000410286 recall: 0.0034464149714222908 F1: 0.0027274243078131847
***************************************************************


In [75]:
print("***************************************************************")
model = DecisionTreeClassifier()
model.fit(traindata, trainlabel)
print(model)
# make predictions
expected = testlabel
predicted = model.predict(testdata)
# summarize the fit of the model

cm = metrics.confusion_matrix(expected, predicted)
print(cm)
tpr = float(cm[0][0])/np.sum(cm[0])
fpr = float(cm[1][1])/np.sum(cm[1])
print("%.3f" %tpr)
print("%.3f" %fpr)
evaluateCM(cm)
print("***************************************************************")


***************************************************************
DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
[[16437   257    57 ...     0     0     0]
 [  148    44     7 ...     0     0     0]
 [   50    17     3 ...     0     0     0]
 ...
 [    1     0     0 ...     0     0     0]
 [    1     0     0 ...     0     0     0]
 [    0     0     0 ...     0     0     0]]
0.864
0.075
Acc: 0.7317246259238337 prec: 0.002660768641334352 recall: 0.0036341434326750354 F1: 0.0030722001419835852
***************************************************************


In [76]:
print("***************************************************************")
model = AdaBoostClassifier(n_estimators=100)
model.fit(traindata, trainlabel)

# make predictions
expected = testlabel
predicted = model.predict(testdata)
# summarize the fit of the model

cm = metrics.confusion_matrix(expected, predicted)
print(cm)
tpr = float(cm[0][0])/np.sum(cm[0])
fpr = float(cm[1][1])/np.sum(cm[1])
print("%.3f" %tpr)
print("%.3f" %fpr)
evaluateCM(cm)

print("***************************************************************")

***************************************************************
[[19017     0     0 ...     0     0     0]
 [  587     0     0 ...     0     0     0]
 [  103     0     0 ...     0     0     0]
 ...
 [    1     0     0 ...     0     0     0]
 [    1     0     0 ...     0     0     0]
 [    1     0     0 ...     0     0     0]]
1.000
0.000
Acc: 0.8435503888888981 prec: 0.001602475943964015 recall: 0.002944740254696747 F1: 0.002075500795745669
***************************************************************


In [77]:
print("***************************************************************")
model = RandomForestClassifier(n_estimators=100)
model = model.fit(traindata, trainlabel)

# make predictions
expected = testlabel
predicted = model.predict(testdata)
# summarize the fit of the model

cm = metrics.confusion_matrix(expected, predicted)
print(cm)
# tpr = float(cm[0][0])/np.sum(cm[0])
# fpr = float(cm[1][1])/np.sum(cm[1])
evaluateCM(cm)

print("***************************************************************")

***************************************************************
[[18997    18     2 ...     0     0     0]
 [  561    24     1 ...     0     0     0]
 [   96     6     0 ...     0     0     0]
 ...
 [    1     0     0 ...     0     0     0]
 [    1     0     0 ...     0     0     0]
 [    1     0     0 ...     0     0     0]]
Acc: 0.8439939658316863 prec: 0.004360444025732532 recall: 0.0051841728457411975 F1: 0.004736763312341666
***************************************************************


In [72]:
def evaluateCM(ConfusionMatrix):
    ConfusionMatrix = np.add(ConfusionMatrix, 0.0000000001)
#     print("sum is ", np.sum(ConfusionMatrix))
    accuracy = np.sum(ConfusionMatrix.diagonal()) / np.sum(ConfusionMatrix)
#     print("sum a1 is ", np.sum(ConfusionMatrix, axis = 1))
    precision = ConfusionMatrix.diagonal() / np.sum(ConfusionMatrix, axis = 1)
#     print("sum a0 is ", np.sum(ConfusionMatrix, axis = 0))
    recall = ConfusionMatrix.diagonal() / np.sum(ConfusionMatrix, axis = 0)

    precision = np.mean(precision)
    recall = np.mean(recall)
    F1 = 2* ((precision * recall ) / (precision + recall))

    print("Acc:", accuracy, "prec:", precision, "recall:", recall, "F1:", F1 )
